// <auto-generated />
namespace MVC_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedpropertiesinmoviestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedpropertiesinmoviestable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003261008196_addedpropertiesinmoviestable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
